[package]
name = "relaks"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.4"
colored = "2.1.0"
criterion = {version = "0.5.1", features = ["html_reports"]}
crossterm = "0.27.0"
inquire = "0.7.5"
rand = "0.8.5"
ratatui = "0.27.0"
ratatui-image = "1.0.1"
rodio = "0.18.1"
